apiVersion: apps/v1

kind: Deployment


metadata:

 name: payments

 namespace: microservices



spec:

 replicas:2


 selector:

  matchLabels:

   app: payments



 template:


  metadata:


   labels:


    app: payments



  spec:


   imagePullSecrets:


   - name: jfrog-secret



   containers:


   - name: payments


     image: hiqode01.jfrog.io/akash-docker/payments:${BUILD_NUMBER}



     ports:


     - containerPort:3004
