apiVersion: apps/v1

kind: Deployment


metadata:

  name: users

  namespace: microservices



spec:


  replicas: 2


  selector:


    matchLabels:


      app: users



  template:


    metadata:


      labels:


        app: users



    spec:


      imagePullSecrets:


      - name: jfrog-secret



      containers:


      - name: users


        image: hiqode01.jfrog.io/docker-local/users:${BUILD_NUMBER}



        ports:


        - containerPort: 3001
